version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - telemetry
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    container_name: kibana
    ports:
      - 5602:5601
    depends_on:
      - elasticsearch
    networks:
      - telemetry
  apm:
    image: docker.elastic.co/apm/apm-server:8.2.3
    container_name: apm
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
    volumes:
      - ./elastic-apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - telemetry

  otel-agent:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.53.0
    container_name: otel-agent
    ports:
      - 4317:4317
    networks:
      - telemetry

volumes:
  data01:
    driver: local
  data02:
    driver: local
networks:
  telemetry:
    driver: bridge
    external: true
