version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - 5602:5601
    depends_on:
      - elasticsearch
    networks:
      - elk
  apm:
    image: docker.elastic.co/apm/apm-server:7.9.0
    environment:
      - apm-server.rum=true
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
    volumes:
      - ./apm-server.yml:/etc/apm-server/apm-server.yml
    networks:
      - elk
volumes:
  data01:
    driver: local
  data02:
    driver: local
networks:
  elk:
    driver: bridge
    external: true